id = "dev-magic"
name = "Dev Magic"
version = "0.0.2"
schema_version = 1
authors = ["Susanta Chakraborty <chak.susanta96@gmail.com>"]
description = "A darker magical theme for Zed Code Editor"
repository = "https://github.com/susanta96/dev-magic"
